# Split context in several files.
# By default only one file with all translations is exported and
# no configuration is required. Your settings for asset pipeline
# are automatically recognized.
#
# If you want to split translations into several files or specify
# locale contexts that will be exported, just use this file to do
# so.
#
# If you're going to use the Rails 3.1 asset pipeline, change
# the following configuration to something like this:
#
#   translations:
#     - file: "app/assets/javascripts/i18n/translations.js"
#
# If you're running an old version, you can use something
# like this:
#
#   translations:
#     - file: "public/javascripts/translations.js"
#       only: "*"
#

translations:
  - file: 'app/javascript/src/javascripts/vendor/i18n-translations.js'
    prefix: "import I18n from 'i18n-js';\nI18n.defaultLocale = document.documentElement.getAttribute('data-default-lang')\nI18n.locale = document.documentElement.lang\n"
    only: ['*.boolean', '*.date', '*.time', '*.datetime', '*.javascript', '*.shared.navbar', '*.templates', '*.activerecord.attributes.itinerary']
